In [1]:
pip install gurobipy

Note: you may need to restart the kernel to use updated packages.


In [2]:
from gurobipy import *

In [ ]:
import pandas as pd

basic_info = pd.read_csv('instance01.csv')
display(basic_info)

Job ID  Stage-1 Processing Time  Stage-2 Processing Time Stage-1 Machines  \
0        1                      9.0                      4.1        1,2,3,4,5   
1        2                      6.2                      0.0        1,2,3,4,5   
2        3                      2.6                      9.1        1,2,3,4,5   
3        4                      8.2                      0.0        1,2,3,4,5   
4        5                      2.2                      7.4        1,2,3,4,5   
5        6                      4.9                      9.2        1,2,3,4,5   
6        7                      9.0                      5.9        1,2,3,4,5   
7        8                      6.9                      6.4        1,2,3,4,5   
8        9                      5.8                      4.8        1,2,3,4,5   
9       10                      1.5                      4.1        1,2,3,4,5   
10      11                      9.6                      0.0        1,2,3,4,5   
11      12                      9.1                      3.4        1,2,3,4,5   
12      13                      3.1                      2.2        1,2,3,4,5   
13      14                      3.8                      3.9        1,2,3,4,5   
14      15                      8.4                      7.0        1,2,3,4,5   
15      16                      7.4                      0.0        1,2,3,4,5   
16      17                      8.4                      3.9        1,2,3,4,5   
17      18                      6.2                      9.2        1,2,3,4,5   
18      19                      9.2                      0.0        1,2,3,4,5   
19      20                      9.3                      7.3        1,2,3,4,5   
20      21                      9.6                      9.1        1,2,3,4,5   
21      22                      9.9                      4.7        1,2,3,4,5   
22      23                      9.9                      8.8        1,2,3,4,5   
23      24                      2.4                      0.0        1,2,3,4,5   
24      25                      2.4                      0.0        1,2,3,4,5   

   Stage-2 Machines  Due Time  
0           2,3,4,5        10  
1               NaN        10  
2           2,3,4,5         5  
3               NaN        10  
4           2,3,4,5         5  
5           2,3,4,5         5  
6           2,3,4,5         5  
7           2,3,4,5        10  
8           2,3,4,5        10  
9           2,3,4,5         5  
10              NaN        10  
11          2,3,4,5         5  
12          2,3,4,5        10  
13          2,3,4,5        10  
14          2,3,4,5         5  
15              NaN        10  
16          2,3,4,5         5  
17          2,3,4,5         5  
18              NaN         5  
19          2,3,4,5        10  
20          2,3,4,5         5  
21          2,3,4,5        10  
22          2,3,4,5        10  
23              NaN         5  
24              NaN         5

In [ ]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('max_colwidth', 100)

In [ ]:
import numpy as np

job_id = basic_info['Job ID']
jobs = len(job_id)
D = basic_info['Due Time']
stage1Time = basic_info['Stage-1 Processing Time']
stage2Time = basic_info['Stage-2 Processing Time']
p = [[0] * jobs for i in range(2)]
for i in range(jobs):
    p[0][i] = stage1Time[i]
for i in range(jobs):
    p[1][i] = stage2Time[i]

available1 = basic_info['Stage-1 Machines']
available2 = basic_info['Stage-2 Machines']
available2 = available2.fillna(0)

machines = 0
for i in range(jobs):
    for item in available1[i]:
        if(item.isdigit()):
            item = int(item)
            if(item > machines):
                machines = item

for i in range(jobs):
    if(available2[i] == 0):
        continue
    for item in available2[i]:
        if(item.isdigit()):
            item = int(item)
            if(item > machines):
                machines = item

available_machine = np.zeros((2,jobs,machines))

for i in range(jobs):
    for item in available1[i]:
        if(item.isdigit()):
            item = int(item)
            available_machine[0][i][item-1] = 1
for i in range(jobs):
    if(available2[i] == 0):
        continue
    for item in available2[i]:
        if(item.isdigit()):
            item = int(item)
            available_machine[1][i][item-1] = 1


In [ ]:
print(available_machine)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[0. 1. 1. 1. 1.]
  [0. 0. 0. 0. 0.]
  [0. 1. 1. 1. 1.]
  [0. 0. 0. 0. 0.]
  [0. 1. 1. 1. 1.]
  [0. 1. 1. 1. 1.]
  [0. 1. 1. 1. 1.]
  [0. 1. 1. 1. 1.]
  [0. 1. 1. 1. 1.]
  [0. 1. 1. 1. 1.]
  [0. 0. 0. 0. 0.]
  [0. 1. 1. 1. 1.]
  [0. 1. 1. 1. 1.]
  [0. 1. 1. 1. 1.]
  [0. 1. 1. 1. 1.]
  [0. 0. 0. 0. 0.]
  [0. 1. 1. 1. 1.]
  [0. 1. 1. 1. 1.]
  [0. 0. 0. 0. 0.]
  [0. 1. 1. 1. 1.]
  [0. 1. 1. 1. 1.]
  [0. 1. 1. 1. 1.]
  [0. 1. 1. 1. 1.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [ ]:
eg1 = Model("eg1")

y = []
for i in range(2):
    y.append([])
    for j in range(jobs):
        y[i].append([])
        for k in range(machines):
            y[i][j].append(eg1.addVar(lb = 0, vtype = GRB.BINARY, name = "y" + str(i+1) + str(j+1) + str(k+1)))

c = []
for i in range(2):
    c.append([])
    for j in range(jobs):
        c[i].append(eg1.addVar(lb = 0, vtype = GRB.CONTINUOUS, name = "c" + str(i+1) + str(j+1)))

T = []
for j in range(jobs):
    T.append(eg1.addVar(lb = 0, vtype = GRB.CONTINUOUS, name = "D" + str(j+1)))

z = []
for i in range(2):
    z.append([])
    for j in range(jobs):
        z[i].append([])
        for a in range(2):
            z[i][j].append([])
            for b in range(jobs):
                z[i][j][a].append([])
                for k in range(machines):
                    z[i][j][a][b].append(eg1.addVar(lb = 0, vtype = GRB.BINARY, name = "z" + str(i+1) + str(j+1) + str(a+1) + str(b+1) + str(k+1)))

Set parameter Username
Academic license - for non-commercial use only - expires 2025-04-11


In [8]:
eg1.setObjective(
    quicksum(T[j] for j in range(jobs)), GRB.MINIMIZE)

M = 0
for i in range(2):
    for j in range(jobs):
        M += p[i][j]

for j in range(jobs):
    eg1.addConstr(c[0][j] <= c[1][j] - p[1][j])
    eg1.addConstr(c[0][j] + 1 + p[1][j] >= c[1][j])
    eg1.addConstr(c[0][j] >= p[0][j])
    eg1.addConstr(T[j] >= c[1][j] - D[j])
    eg1.addConstr(T[j] >= 0)
for i in range(2):
    for j in range(jobs):
        out = True
        for a in range(machines):
            if(available_machine[i][j][a] == 1):
                out = False
                break
        if(out == True):
            continue
        eg1.addConstr(quicksum(y[i][j][k] for k in range(machines)) == 1)
for i in range(2):
    for j in range(jobs):
        for k in range(machines):
            eg1.addConstr(available_machine[i][j][k] - y[i][j][k] >= 0)

for i in range(2):
    for j in range(jobs):
        for a in range(2):
            for b in range(jobs):
                for k in range(machines):
                    if(i == a and j == b):
                        continue
                    eg1.addConstr(y[i][j][k] + y[a][b][k] <= (z[i][j][a][b][k] + z[a][b][i][j][k] + 1))
                    eg1.addConstr(c[i][j] + p[a][b] - c[a][b] <= M * (1 - z[i][j][a][b][k]))

eg1.optimize()  

Gurobi Optimizer version 11.0.1 build v11.0.1rc0 (win64 - Windows 11.0 (22631.2))

CPU model: 12th Gen Intel(R) Core(TM) i7-1260P, instruction set [SSE2|AVX|AVX2]
Thread count: 12 physical cores, 16 logical processors, using up to 16 threads

Optimize a model with 24918 rows, 12825 columns and 86415 nonzeros
Model fingerprint: 0x3f01a5bc
Variable types: 75 continuous, 12750 integer (12750 binary)
Coefficient statistics:
  Matrix range     [1e+00, 3e+02]
  Objective range  [1e+00, 1e+00]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 3e+02]
Presolve removed 11281 rows and 4746 columns
Presolve time: 0.13s
Presolved: 13637 rows, 8079 columns, 43033 nonzeros
Variable types: 58 continuous, 8021 integer (8021 binary)
Found heuristic solution: objective 2187.3000000

Root relaxation: objective 1.113000e+02, 109 iterations, 0.01 seconds (0.01 work units)

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    Bes

KeyboardInterrupt: 

Exception ignored in: 'gurobipy.logcallbackstub'
Traceback (most recent call last):
  File "c:\Users\seanh\anaconda3\lib\site-packages\ipykernel\iostream.py", line 518, in write
    def write(self, string: str) -> Optional[int]:  # type:ignore[override]
KeyboardInterrupt: 


 195351 148198  402.20000  141   95  516.70000  111.30000  78.5%  47.5 1140s


In [ ]:
print(eg1 == GRB.OPTIMAL)

False


In [ ]:
print("total tardiness = ", eg1.objVal)

print("whether stage i of job j is processed in machine k:")
for j in range(jobs):
    for i in range(2):
        for k in range(machines):
            print(y[i][j][k].x, "\t", end = "")
        print("")
    print("")

print("the completion time of stage i of job j:")
for j in range(jobs):
    for i in range(2):
        print(c[i][j].x, "\t", end = "")
    print("")

print("the tadiness of job j:")
for j in range(jobs):
    print(T[j].x, "\t", end = "")

# print("whether stage i of job j is processed in front of stage i' of job j' in machine k:")
# for i in range(2):
#     for j in range(jobs):
#         for a in range(2):
#             for b in range(jobs):
#                 for k in range(machines):
#                     print("is stage " + str(i+1)  + " of job " + str(j+1) + " in front of stage " + str(a+1) + " job " + str(b+1) + " in machine " + str(k+1))
#                     print(z[i][j][a][b][k].x, "\t", end="")
#                     print()

total tardiness =  2.2
whether stage i of job j is processed in machine k:
1.0 	0.0 	
1.0 	0.0 	

0.0 	1.0 	
0.0 	1.0 	

1.0 	0.0 	
1.0 	0.0 	

the completion time of stage i of job j:
5.3 	6.6 	
1.6 	3.0 	
0.7 	2.6 	
the tadiness of job j:
1.6 	0.0 	0.6 	

In [ ]:
eg2 = Model("eg2")

y = []
for i in range(2):
    y.append([])
    for j in range(jobs):
        y[i].append([])
        for k in range(machines):
            y[i][j].append(eg2.addVar(lb = 0, vtype = GRB.BINARY, name = "y" + str(i+1) + str(j+1) + str(k+1)))

c = []
for i in range(2):
    c.append([])
    for j in range(jobs):
        c[i].append(eg2.addVar(lb = 0, vtype = GRB.CONTINUOUS, name = "c" + str(i+1) + str(j+1)))

T = []
for j in range(jobs):
    T.append(eg2.addVar(lb = 0, vtype = GRB.CONTINUOUS, name = "D" + str(j+1)))

z = []
for i in range(2):
    z.append([])
    for j in range(jobs):
        z[i].append([])
        for a in range(2):
            z[i][j].append([])
            for b in range(jobs):
                z[i][j][a].append([])
                for k in range(machines):
                    z[i][j][a][b].append(eg2.addVar(lb = 0, vtype = GRB.BINARY, name = "z" + str(i+1) + str(j+1) + str(a+1) + str(b+1) + str(k+1)))

w = eg2.addVar(lb = 0, vtype = GRB.CONTINUOUS, name = "w")

In [ ]:
obj = eg1.objVal
print(obj)

2.2


In [ ]:
eg2.setObjective(w, GRB.MINIMIZE)

M = 0
for i in range(2):
    for j in range(jobs):
        M += p[i][j]

eg2.addConstrs(w >= c[1][j] for j in range(jobs))

for j in range(jobs):
    eg2.addConstr(c[0][j] <= c[1][j] - p[1][j])
    eg2.addConstr(c[0][j] + 1 + p[1][j] >= c[1][j])
    eg2.addConstr(c[0][j] >= p[0][j])
    eg2.addConstr(T[j] >= c[1][j] - D[j])
    eg2.addConstr(T[j] >= 0)

eg2.addConstr(quicksum(T[j] for j in range(jobs)) <= obj)

for i in range(2):
    for j in range(jobs):
        out = True
        for a in range(machines):
            if(available_machine[i][j][a] == 1):
                out = False
                break
        if(out == True):
            continue
        eg2.addConstr(quicksum(y[i][j][k] for k in range(machines)) == 1)
for i in range(2):
    for j in range(jobs):
        for k in range(machines):
            eg2.addConstr(available_machine[i][j][k] - y[i][j][k] >= 0)

for i in range(2):
    for j in range(jobs):
        for a in range(2):
            for b in range(jobs):
                for k in range(machines):
                    if(i == a and j == b):
                        continue
                    eg2.addConstr(y[i][j][k] + y[a][b][k] <= (z[i][j][a][b][k] + z[a][b][i][j][k] + 1))
                    eg2.addConstr(c[i][j] + p[a][b] - c[a][b] <= M * (1 - z[i][j][a][b][k]))
eg2.optimize()

Gurobi Optimizer version 11.0.1 build v11.0.1rc0 (win64 - Windows 11.0 (22631.2))

CPU model: 12th Gen Intel(R) Core(TM) i7-1260P, instruction set [SSE2|AVX|AVX2]
Thread count: 12 physical cores, 16 logical processors, using up to 16 threads

Optimize a model with 157 rows, 94 columns and 477 nonzeros
Model fingerprint: 0xfcc504b7
Variable types: 10 continuous, 84 integer (84 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+01]
  Objective range  [1e+00, 1e+00]
  Bounds range     [1e+00, 1e+00]
  RHS range        [7e-01, 9e+00]
Presolve removed 100 rows and 56 columns
Presolve time: 0.00s
Presolved: 57 rows, 38 columns, 163 nonzeros
Variable types: 8 continuous, 30 integer (30 binary)
Found heuristic solution: objective 6.6000000
Found heuristic solution: objective 5.6000000

Root relaxation: objective 4.000000e+00, 18 iterations, 0.00 seconds (0.00 work units)

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Inc

In [ ]:
print(eg2 == GRB.OPTIMAL)

False


In [ ]:
print(eg2.ObjVal)


5.6
